version: "3.7"

services:
  broker:
    container_name: mosquitto_broker
    image: eclipse-mosquitto:1.6
    volumes:
      - ./config:/mosquitto/mosquitto.conf:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    networks:
      - localnet
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    restart: always

  node-red:
    depends_on:
      - broker
    image: nodered/node-red:latest
    volumes:
      - "./node-red:/data"
    networks:
      - localnet
    ports:
      - "1880:1880"
    environment:
      - TZ=America/Sao_Paulo


volumes:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
  node-red-data:

networks:
  localnet:
    driver: bridge
    driver_opts:
          com.docker.network.enable_ipv6: "true"